services:
  - type: web
    name: crime-patrol-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        value: 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
